name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
      - name: install dependencies
        run: opam install . --deps-only --with-test
      - name: test
        run: opam exec -- dune runtest
      - name: test-format
        run: opam exec -- dune build @fmt
