name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-version: 22
        with:
          path: |
            /home/runner/.opam
            _build
          key:
            opam-${{ env.cache-version }}-build-${{ hashFiles('**/*.opam.locked') }}
          restore-keys: |
            opam-${{ env.cache-version }}-build-
            opam-${{ env.cache-version }}-
      - name: setup OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.10.0
      - name: install dependencies
        run: opam install . --deps-only --with-doc --with-test
      - name: test
        run: opam exec -- dune test
      - name: test-format
        run: opam exec -- dune build @fmt
